// ============================================================
//  server/lib/pdfReport.js — weekly parent report (pdfkit)
// ============================================================

import PDFDocument from 'pdfkit';

export function streamWeeklyReportPdf(res, data) {
  const doc = new PDFDocument({ size: 'A4', margin: 48 });
  doc.pipe(res);

  const { student, parentName, summary, lessons, strongest, weakest, teacherNote, period } = data;

  // Header band
  doc.rect(0, 0, doc.page.width, 110).fill('#2563eb');
  doc.fillColor('white').font('Helvetica-Bold').fontSize(22).text('D-DASH', 48, 36);
  doc.font('Helvetica').fontSize(12).text('Weekly Progress Report', 48, 64);
  doc.fontSize(10).text(period || '', 48, 84);

  doc.fillColor('#0b2b5e').font('Helvetica-Bold').fontSize(16).text(student.name, 48, 130);
  doc.font('Helvetica').fontSize(11).fillColor('#64748b').text(`For: ${parentName || 'Parent/Guardian'}`, 48, 152);

  // Summary cards
  let y = 188;
  const cardW = (doc.page.width - 48 * 2 - 12 * 3) / 4;
  const cards = [
    { label: 'Lessons done',  value: String(summary.lessonsCompleted || 0) },
    { label: 'Sections',      value: String(summary.sectionsCompleted || 0) },
    { label: 'Accuracy',      value: summary.accuracy == null ? '—' : `${Math.round(summary.accuracy)}%` },
    { label: 'vs last week',  value: summary.accuracyDelta == null ? '—' : `${summary.accuracyDelta > 0 ? '+' : ''}${Math.round(summary.accuracyDelta)}%` },
  ];
  cards.forEach((c, i) => {
    const x = 48 + i * (cardW + 12);
    doc.roundedRect(x, y, cardW, 62, 10).fill('#f1f5f9');
    doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(9).text(c.label.toUpperCase(), x + 10, y + 10, { width: cardW - 20 });
    doc.fillColor('#0b2b5e').font('Helvetica-Bold').fontSize(17).text(c.value, x + 10, y + 28, { width: cardW - 20 });
  });
  y += 80;

  // Call-outs
  if (strongest || weakest) {
    doc.font('Helvetica').fontSize(11).fillColor('#0b2b5e');
    if (strongest) { doc.font('Helvetica-Bold').text('Strongest: ', 48, y, { continued: true }).font('Helvetica').text(strongest); y += 18; }
    if (weakest)   { doc.font('Helvetica-Bold').text('Needs practice: ', 48, y, { continued: true }).font('Helvetica').text(weakest); y += 18; }
    y += 6;
  }

  if (teacherNote) {
    doc.roundedRect(48, y, doc.page.width - 96, 60, 10).fill('#f8fafd').stroke('#e2e8f0');
    doc.fillColor('#64748b').font('Helvetica-Bold').fontSize(9).text('TEACHER NOTE', 58, y + 10);
    doc.fillColor('#0b2b5e').font('Helvetica').fontSize(11).text(teacherNote, 58, y + 26, { width: doc.page.width - 116, height: 30 });
    y += 76;
  }

  // Lessons table
  doc.fillColor('#0b2b5e').font('Helvetica-Bold').fontSize(13).text('Lessons studied', 48, y);
  y += 20;

  const cols = [
    { label: 'Lesson',   width: 80  },
    { label: 'Title',    width: 210 },
    { label: 'Accuracy', width: 60  },
    { label: 'Status',   width: 80  },
    { label: 'Date',     width: 70  },
  ];
  const rowX = (i) => 48 + cols.slice(0, i).reduce((a, c) => a + c.width, 0);
  // header row
  doc.rect(48, y, doc.page.width - 96, 22).fill('#f1f5f9');
  doc.fillColor('#0b2b5e').font('Helvetica-Bold').fontSize(10);
  cols.forEach((c, i) => doc.text(c.label, rowX(i) + 6, y + 7, { width: c.width - 8 }));
  y += 22;

  doc.font('Helvetica').fontSize(10);
  (lessons || []).forEach(l => {
    if (y > doc.page.height - 80) { doc.addPage(); y = 48; }
    const acc = l.accuracy == null ? '—' : `${Math.round(l.accuracy)}%`;
    doc.fillColor('#0b2b5e').text(`U${l.unit} · L${l.lesson_num}`, rowX(0) + 6, y + 5, { width: cols[0].width - 8 });
    doc.text(l.title || '', rowX(1) + 6, y + 5, { width: cols[1].width - 8 });
    doc.text(acc, rowX(2) + 6, y + 5, { width: cols[2].width - 8 });
    doc.text(l.status || '', rowX(3) + 6, y + 5, { width: cols[3].width - 8 });
    doc.fillColor('#64748b').text(l.date || '', rowX(4) + 6, y + 5, { width: cols[4].width - 8 });
    y += 22;
    doc.strokeColor('#eef3f9').moveTo(48, y).lineTo(doc.page.width - 48, y).stroke();
  });
  if (!(lessons || []).length) {
    doc.fillColor('#64748b').text('No lessons completed this period.', 54, y + 6);
  }

  // Footer
  doc.fontSize(9).fillColor('#94a3b8').text('Generated by D-DASH — contact your child\'s teacher for more detail.',
    48, doc.page.height - 50, { width: doc.page.width - 96, align: 'center' });

  doc.end();
}
